definitions:
  author.addForm:
    properties:
      birthday:
        type: string
      name:
        description: binding:"required"修饰的字段，若接收为空值，则报错，是必须字段
        type: string
    required:
    - birthday
    - name
    type: object
  author.addOutput:
    properties:
      code:
        default: 0
        type: integer
      errMsg:
        type: string
      msg:
        default: OK
        type: string
    type: object
  author.getOutput:
    properties:
      code:
        default: 0
        type: integer
      data:
        description: 数据
        items:
          $ref: '#/definitions/models.AuthorOUtput'
        type: array
      errMsg:
        type: string
      hasNext:
        description: 是否有下一页
        type: boolean
      hasPerv:
        description: 是否有上一页
        type: boolean
      msg:
        default: OK
        type: string
      page:
        default: 1
        description: 当前页
        type: integer
      pages:
        description: 总页数
        type: integer
      size:
        default: 10
        description: 当前页的数量
        type: integer
      total:
        description: 总数
        type: integer
    type: object
  models.AuthorOUtput:
    properties:
      birthday:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /author:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - default: 1
        description: 当前页
        in: query
        name: page
        type: integer
      - default: 10
        description: 当前页的数量
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/author.getOutput'
      security:
      - ApiKeyAuth: []
      tags:
      - 作者相关接口
    post:
      consumes:
      - application/json
      description: 添加一个作者信息 包括名字和生日
      parameters:
      - description: 作者生日
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/author.addForm'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/author.addOutput'
      security:
      - ApiKeyAuth: []
      summary: 添加一个作者
      tags:
      - 作者相关接口
swagger: "2.0"
