definitions:
  models.UserOutput:
    properties:
      avatar:
        type: string
      email:
        type: string
      gender:
        type: integer
      id:
        type: integer
      nickname:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  response.BaseResponse:
    properties:
      code:
        default: 0
        type: integer
      errMsg:
        type: string
    type: object
  users.UserResponse:
    properties:
      code:
        default: 0
        type: integer
      data:
        $ref: '#/definitions/models.UserOutput'
      errMsg:
        type: string
    type: object
info:
  contact: {}
  description: Listen and Server
  version: 0.0.1
paths:
  /users:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新用户信息接口
      parameters:
      - in: formData
        maxLength: 20
        minLength: 8
        name: Email
        required: true
        type: string
      - in: formData
        maximum: 2
        minimum: 0
        name: gender
        required: true
        type: integer
      - in: formData
        maxLength: 10
        minLength: 4
        name: nickname
        required: true
        type: string
      - in: formData
        maxLength: 11
        minLength: 11
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "400":
          description: 错误的请求
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: 更新用户信息
      tags:
      - 用户相关接口
  /users/{id}:
    get:
      consumes:
      - application/urlencoded
      description: 查询用户信息接口
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/users.UserResponse'
        "400":
          description: 错误的请求
          schema:
            $ref: '#/definitions/users.UserResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/users.UserResponse'
      security:
      - ApiKeyAuth: []
      summary: 用户信息
      tags:
      - 用户相关接口
  /users/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户登录接口
      parameters:
      - in: formData
        maxLength: 30
        minLength: 9
        name: password
        required: true
        type: string
      - in: formData
        maximum: 1
        minimum: 0
        name: role
        type: integer
      - in: formData
        maxLength: 20
        minLength: 8
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "400":
          description: 错误的请求
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: 登录
      tags:
      - 用户相关接口
  /users/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户注册接口
      parameters:
      - in: formData
        maxLength: 30
        minLength: 9
        name: password
        required: true
        type: string
      - in: formData
        maximum: 1
        minimum: 0
        name: role
        type: integer
      - in: formData
        maxLength: 20
        minLength: 8
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "400":
          description: 错误的请求
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: 添加一个用户
      tags:
      - 用户相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
